# Generated by Django 5.2.7 on 2026-02-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_pizza_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='price',
            new_name='large_price',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default=None, upload_to='pizzas/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='medium_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='small_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
